/* This file has been generated from /home/pat/paparazzi3/conf/airframes/linuxfc.xml */
/* Please DO NOT EDIT */

#ifndef AIRFRAME_H
#define AIRFRAME_H 

#define AIRFRAME_NAME "LINUXFC"
#define AC_ID 5
#define MD5SUM ((uint8_t*)"\275\207\220\156\253\304\016\266\262\345\127\055\375\015\230\203")

#define SERVOS_NB 4

#define SERVO_AILERON 0
#define SERVO_AILERON_NEUTRAL 128
#define SERVO_AILERON_TRAVEL_UP 0.013125
#define SERVO_AILERON_TRAVEL_DOWN 0.0133333333333
#define SERVO_AILERON_MAX 254
#define SERVO_AILERON_MIN 0

#define SERVO_ELEVATOR 1
#define SERVO_ELEVATOR_NEUTRAL 128
#define SERVO_ELEVATOR_TRAVEL_UP 0.013125
#define SERVO_ELEVATOR_TRAVEL_DOWN 0.0133333333333
#define SERVO_ELEVATOR_MAX 254
#define SERVO_ELEVATOR_MIN 0

#define SERVO_THROTTLE 2
#define SERVO_THROTTLE_NEUTRAL 128
#define SERVO_THROTTLE_TRAVEL_UP 0.013125
#define SERVO_THROTTLE_TRAVEL_DOWN 0.0133333333333
#define SERVO_THROTTLE_MAX 254
#define SERVO_THROTTLE_MIN 0

#define SERVO_RUDDER 3
#define SERVO_RUDDER_NEUTRAL 128
#define SERVO_RUDDER_TRAVEL_UP 0.013125
#define SERVO_RUDDER_TRAVEL_DOWN 0.0133333333333
#define SERVO_RUDDER_MAX 254
#define SERVO_RUDDER_MIN 0


#define COMMAND_THROTTLE 0
#define COMMAND_ROLL 1
#define COMMAND_PITCH 2
#define COMMAND_RUDDER 3
#define COMMANDS_NB 4
#define COMMANDS_FAILSAFE {0,0,0,0}


#define SetActuatorsFromCommands(values) { \
  uint16_t servo_value;\
  float command_value;\
  command_value = values[COMMAND_THROTTLE];\
  command_value *= command_value>0 ? SERVO_THROTTLE_TRAVEL_UP : SERVO_THROTTLE_TRAVEL_DOWN;\
  servo_value = SERVO_THROTTLE_NEUTRAL + (int16_t)(command_value);\
  actuators[SERVO_THROTTLE] = ChopServo(servo_value, SERVO_THROTTLE_MIN, SERVO_THROTTLE_MAX);\
\
  Actuator(SERVO_THROTTLE) = SERVOS_TICS_OF_USEC(actuators[SERVO_THROTTLE]);\
\
  command_value = values[COMMAND_ROLL];\
  command_value *= command_value>0 ? SERVO_AILERON_TRAVEL_UP : SERVO_AILERON_TRAVEL_DOWN;\
  servo_value = SERVO_AILERON_NEUTRAL + (int16_t)(command_value);\
  actuators[SERVO_AILERON] = ChopServo(servo_value, SERVO_AILERON_MIN, SERVO_AILERON_MAX);\
\
  Actuator(SERVO_AILERON) = SERVOS_TICS_OF_USEC(actuators[SERVO_AILERON]);\
\
  command_value = values[COMMAND_RUDDER];\
  command_value *= command_value>0 ? SERVO_RUDDER_TRAVEL_UP : SERVO_RUDDER_TRAVEL_DOWN;\
  servo_value = SERVO_RUDDER_NEUTRAL + (int16_t)(command_value);\
  actuators[SERVO_RUDDER] = ChopServo(servo_value, SERVO_RUDDER_MIN, SERVO_RUDDER_MAX);\
\
  Actuator(SERVO_RUDDER) = SERVOS_TICS_OF_USEC(actuators[SERVO_RUDDER]);\
\
  command_value = values[COMMAND_PITCH];\
  command_value *= command_value>0 ? SERVO_ELEVATOR_TRAVEL_UP : SERVO_ELEVATOR_TRAVEL_DOWN;\
  servo_value = SERVO_ELEVATOR_NEUTRAL + (int16_t)(command_value);\
  actuators[SERVO_ELEVATOR] = ChopServo(servo_value, SERVO_ELEVATOR_MIN, SERVO_ELEVATOR_MAX);\
\
  Actuator(SERVO_ELEVATOR) = SERVOS_TICS_OF_USEC(actuators[SERVO_ELEVATOR]);\
\
  ActuatorsCommit();\
}
#define SECTION_AUTO1 1
#define AUTO1_MAX_ROLL 0.85
#define AUTO1_MAX_PITCH 0.6

#define SECTION_adc 1
#define ADC_CHANNEL_IR1 ADC_1
#define ADC_CHANNEL_IR2 ADC_2
#define ADC_CHANNEL_IR_TOP ADC_3
#define ADC_CHANNEL_IR_NB_SAMPLES 16

#define SECTION_INFRARED 1
#define IR_ADC_IR1_NEUTRAL 400
#define IR_ADC_IR2_NEUTRAL 400
#define IR_ADC_TOP_NEUTRAL 400
#define IR_LATERAL_CORRECTION 1.
#define IR_LONGITUDINAL_CORRECTION 1.
#define IR_VERTICAL_CORRECTION 1.5
#define IR_HORIZ_SENSOR_TILTED 1
#define IR_IR2_SIGN -1
#define IR_TOP_SIGN -1
#define IR_ROLL_NEUTRAL_DEFAULT -3.6
#define IR_PITCH_NEUTRAL_DEFAULT 5
#define IR_CORRECTION_UP 1.
#define IR_CORRECTION_DOWN 1.
#define IR_CORRECTION_LEFT 1.
#define IR_CORRECTION_RIGHT 1.

#define SECTION_BAT 1
#define MILLIAMP_AT_FULL_THROTTLE 2000
#define CATASTROPHIC_BAT_LEVEL -1

#define SECTION_MISC 1
#define MINIMUM_AIRSPEED 12.
#define NOMINAL_AIRSPEED 15.
#define MAXIMUM_AIRSPEED 25.
#define CARROT 5.
#define KILL_MODE_DISTANCE (1.5*MAX_DIST_FROM_HOME)
#define CONTROL_RATE 60
#define ALT_KALMAN_ENABLED TRUE
#define DEFAULT_CIRCLE_RADIUS 80.
#define MIN_CIRCLE_RADIUS 50.

#define SECTION_VERTICAL CONTROL 1
#define V_CTL_ALTITUDE_PGAIN -0.04
#define V_CTL_ALTITUDE_MAX_CLIMB 2.
#define V_CTL_AUTO_THROTTLE_NOMINAL_CRUISE_THROTTLE 0.35
#define V_CTL_AUTO_THROTTLE_MIN_CRUISE_THROTTLE 0.25
#define V_CTL_AUTO_THROTTLE_MAX_CRUISE_THROTTLE 0.80
#define V_CTL_AUTO_THROTTLE_LOITER_TRIM 1500
#define V_CTL_AUTO_THROTTLE_DASH_TRIM -1000
#define V_CTL_AUTO_THROTTLE_CLIMB_THROTTLE_INCREMENT 0.1
#define V_CTL_AUTO_THROTTLE_PGAIN -0.02
#define V_CTL_AUTO_THROTTLE_IGAIN 0.1
#define V_CTL_AUTO_THROTTLE_PITCH_OF_VZ_PGAIN 0.1
#define V_CTL_AUTO_PITCH_PGAIN -0.05
#define V_CTL_AUTO_PITCH_IGAIN 0.075
#define V_CTL_AUTO_PITCH_MAX_PITCH 0.35
#define V_CTL_AUTO_PITCH_MIN_PITCH -0.35
#define V_CTL_THROTTLE_SLEW 0.5

#define SECTION_HORIZONTAL CONTROL 1
#define H_CTL_COURSE_PGAIN -0.8
#define H_CTL_ROLL_MAX_SETPOINT 0.7
#define H_CTL_PITCH_MAX_SETPOINT 0.5
#define H_CTL_PITCH_MIN_SETPOINT -0.5
#define H_CTL_PITCH_PGAIN -10000.
#define H_CTL_PITCH_DGAIN 1.5
#define H_CTL_ELEVATOR_OF_ROLL 2500
#define H_CTL_ROLL_ATTITUDE_GAIN -7500
#define H_CTL_ROLL_RATE_GAIN -1500

#define SECTION_AGGRESSIVE 1
#define AGR_BLEND_START 20
#define AGR_BLEND_END 10
#define AGR_CLIMB_THROTTLE 0.6
#define AGR_CLIMB_PITCH 0.20
#define AGR_DESCENT_THROTTLE 0.1
#define AGR_DESCENT_PITCH -0.15
#define AGR_CLIMB_NAV_RATIO 0.8
#define AGR_DESCENT_NAV_RATIO 1.0

#define SECTION_FAILSAFE 1
#define FAILSAFE_DELAY_WITHOUT_GPS 1
#define FAILSAFE_DEFAULT_THROTTLE 0.3
#define FAILSAFE_DEFAULT_ROLL 0.3
#define FAILSAFE_DEFAULT_PITCH 0.5
#define FAILSAFE_HOME_RADIUS 100


#endif // AIRFRAME_H
